checkbox5
Sempayy/My-horror-UI-chip pull request #4
Opened 2022-05-06 17:32 UTC by Sempayy

2022-05-06 18:40 UTC, stergen requested changes

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +  width: 100%;
why do you need this width? `div` is blocj it takes `100%` by default

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +  height: 10rem;
you add height, marging and padding. Why do you need so many thing?

2022-05-06 18:40 UTC, stergen commented on assets/style.css
>    background: #fff;
You don't need background

2022-05-06 18:40 UTC, stergen commented on assets/style.css
>    display: flex;
WHy do you need flex there?

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +.scrolltab__box {
why `box`?
Should you use something uniq?
Examples: `listContainer`, `list-box`, etc...
But if you remove all unnessary stles you will see, that this class has only `overflow` and `position` and maybe you will you another class name

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +.checkbox__box {
Why does `checkbox__box` stay in `/* Linear background */` section?

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +#box {
please don't use styles for `id` if it possible.
But `box` again. Are you kidding me?

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +.check__input {
sorry, but it's wrong name. You hace check box inside the label. In BEM metadologic you must use structure 
B - Block
E - Element
M - Modificator 

It's mean you have two option for `label`:
1. You use label like new BLOCK, it's mean class must be `input-label` or `label`, but if this label specific for checkbox, you need add MODIFICATOR like: `label--checkbox` or `input-label--checkbox`.
2. This labe should always be with checkbox is mean you must make label like a BLOCK and checkbox must be like a Element. Example: `baseChekbox`, checkbox class is `baseChekbox __checkbox` and input is `baseChekbox __checkbox__input`

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +  background-image: url("data:image/svg+xml,%3Csvg width='14' height='2' viewBox='0 0 14 2' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cline x1='1' y1='1' x2='13' y2='1' stroke='white' stroke
if you use `data:image` why do you need `*.svg` files in the project?

2022-05-06 18:40 UTC, stergen commented on assets/style.css
> +.check {
this name doesn't provide real vision and sounds like a modificatory

2022-05-09 16:55 UTC, stergen requested changes
Much better, but we can make it better

2022-05-09 16:55 UTC, stergen commented on assets/style.css
> +.container__forspace {
Why do you need `.container` if your forspace isn't element of container

2022-05-09 16:55 UTC, stergen commented on assets/style.css
>    display: flex;
I have still see `flex`

2022-05-09 16:55 UTC, stergen commented on assets/style.css
> +.list-container__normalize-list {
Good point `normalize-list` but your name sound like a modificatory it's mean you mast use `--normalize-list`

2022-05-09 16:55 UTC, stergen commented on assets/style.css
> +  overflow-y: scroll;
So if it's modificatory it's mean you can't use overflow, because this field set extra thing

2022-05-09 16:55 UTC, stergen commented on index.html
> +          >Disabled checkbox
Don't move `>` to the next line

2022-05-09 20:15 UTC, Sempayy commented on assets/style.css
> +.label-checkbox__input {
I didn’t quite understand the comment, because according to BEM, checkboxes (for which the container is <label>) are a separate element

2022-05-10 06:15 UTC, stergen requested changes

2022-05-10 06:15 UTC, stergen commented on assets/style.css
> +.base--label--checkbox {
But if 3 is true you will have to make block `.base-label`. I know it will be empty but it must be

2022-05-10 06:15 UTC, stergen commented on assets/style.css
> +.base--checkbox {
It's the container so you don need double minus, use only one, it's not a modificatory

2022-05-10 06:15 UTC, stergen commented on assets/style.css
> +  font-size: 10px;
This font size you use for `em`, but if I want to use checkbox without label like a wrap, you system will broken. 

For example how I can use label:
```
<span class="base--checkbox">
  <input class="base--checkbox__input" id="forTest" type="checkbox" />
  <span class="base--checkbox__check-icon"></span>
</span>
<div class="product">
  <label for="forTest">Test product</label>
</div>
```

2022-05-13 14:24 UTC, stergen approved these changes

2022-05-17 14:56 UTC, merged